inherit_gem:
  prettier: rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rails_picture.gemspec'
