name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: gems-
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.27
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake
